- name: variables from file
  hosts: localhost
  vars_files: #decalring variable file name
  - vars.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "hi i am madhavi i am learning {{course}} {{trainer}} {{duration}}"