- name: calling variables from other file
  hosts: localhost
  var_files:
  - vars.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "hi i am madhavi i am learning {{course}}{{trainer}}{{duration}}"