- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: linux command execution
    ansible.builtin.command: id expense #run a command and take output from that comand
    register: user
    ignore_errors: true
  
  - name: saying hello
    ansible.builtin.debug:
     msg: "hello {{user}}"