- name: default variable declaration
  hosts: localhost
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "hello {{user | default ('dummy') }}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "my name is madhavi"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"