- name: default variable declaration
  hosts: localhost
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "hello {{user | default ('dummy') }}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "i am madhavi"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "HELLO SHIVA"
  tasks:
  - name: lower case
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"