- name: default variable declaration
  hosts: localhost
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "hello {{user | default ('dummy') }}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "i am madhavi"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "HELLO SHIVA"
  tasks:
  - name: lower case
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"

- name: to remove dublicates
  hosts: localhost
  vars:
   numbers: [1, 3, 3, 2, 2, 5, 5, 3, 1, 6, 6]
  tasks:
  - name: remove dublicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique}}"

- name: mini and max filttering
  hosts: localhost
  vars:
   age: [ 32, 29, 6, 4, 63]
  tasks:
  - name: printing min and max numbers
    ansible.builtin.debug:
     msg: "min age: {{age | min}} maximum age: {{age | max}}"

- name: dictionary to item/list converting
  hosts: localhost
  vars:
   my_dict:
      couse: devops
      duration: 3 months
      trainer: shiva
  tasks:
  - name: before convert
    ansible.builtin.debug:
     msg: "{{my_dict }}"
  - name: after convert
    ansible.builtin.debug:
     msg: "{{my_dict | dict2items }}"  #converting dictionary/map/keyvalue pairs to items/list

- name: items to dictionary converting
  hosts: localhost
  vars:
    list:
    - shiva
    - madhu
    - loukya
  tasks:
  - name: befor convert
    ansible.builtin.debug:
     msg: "{{list}}"
  - name: after convert
    ansible.builtin.debug:
     msg: "{{list | items2dict }}"