- name: default variable declaration
  hosts: localhost
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "hello {{user | default ('dummy') }}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "i am madhavi"
  tasks:
  - name: upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: word convert
  hosts: localhost
  vars:
   greetings: "HELLO SHIVA"
  tasks:
  - name: lower case
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"

- name: to remove dublicates
  hosts: localhost
  vars:
   numbers: [1, 3, 3, 2, 2, 5, 5, 3, 1, 6, 6]
  tasks:
  - name: remove dublicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique}}"