- name: installing packages using loop condition
  hosts: web
  become: yes
  tasks:
  # - name: installing packages
  #   ansible.builtin.dnf:
  #    name: "{{ item }}" 
  #    state: latest
    
  #   loop:
  #     - nginx
  #     - mysql
  #     - postfix
  #installing some packages and uninstalling some packages

- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
     name: "{{ item.name}}"
     state: "{{ item.state}}"
    loop:
     - {name: 'nginx', state: 'absent'} ###items
     - {name: 'mysql', state: 'absent'} ###items
     - {name: 'postfix', state: 'latest'} ###items